[package]
name = "vmsh"
version = "0.0.0"
edition = "2021"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/d-e-s-o/vmsh.git"
description = """
Transparently run a shell (or other binary) in a VM.
"""

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false
panic = "abort"

[features]
test = []

[build-dependencies]
grev = { version = "0.1.3" }

[dependencies]
anyhow = { version = "1" }
clap = { version = "4", features = ["derive"] }
libc = { version = "0.2" }
# TODO: Switch to release >1.17.4 once published.
libkrun = { git = "https://github.com/containers/libkrun.git", rev = "44312fdfa105256f1988ea8cdfbde8ed1532c944" }
# Explicitly pin the otherwise transitive `vm-memory` dependency, to fix
# version resolution otherwise resulting in broken build.
_vm-memory_unused = { package = "vm-memory", version = "=0.17.1" }

[dev-dependencies]
tempfile = { version = "3", default-features = false }
vmsh = { path = ".", features = ["test"] }

[lints.rust]
deprecated-safe = "warn"
future-incompatible = "warn"
keyword-idents = "warn"
let-underscore = "warn"
missing-debug-implementations = "warn"
missing-docs = "warn"
trivial-numeric-casts = "warn"
unsafe-op-in-unsafe-fn = "warn"
unused = "warn"

[lints.clippy]
collapsible-else-if = "allow"
collapsible-if = "allow"
diverging-sub-expression = "allow"
let-and-return = "allow"
let-unit-value = "allow"
module-inception = "allow"
type-complexity = "allow"
absolute-paths = "warn"
allow-attributes = "warn"
clone-on-ref-ptr = "warn"
dbg-macro = "warn"
derive-partial-eq-without-eq = "warn"
doc-markdown = "warn"
join-absolute-paths = "warn"
large-enum-variant = "warn"
multiple-unsafe-ops-per-block = "warn"
redundant-closure-for-method-calls = "warn"
unchecked-time-subtraction = "warn"
undocumented-unsafe-blocks = "warn"
uninlined-format-args = "warn"
use-self = "warn"
wildcard-imports = "warn"
