name: Test

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  # Build with only line information enabled to decrease compilation
  # time and binary sizes in CI. This option is assumed to only have
  # marginal effects on the generated code, likely only in terms of
  # section arrangement. See
  # https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo
  RUSTFLAGS: '-D warnings -C debuginfo=line-tables-only'

jobs:
  build:
    name: Build [${{ matrix.profile }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        profile: [dev, release]
    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Build
      run: cargo build --profile=${{ matrix.profile }}
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: d-e-s-o/build-linux@a2c2581c6b44879b6070699618be648480a122c5
        id: build
        with:
          kernel-repo: 'gregkh/linux'
          rev: 'v6.18.35'
          config: 'var/linux-config-minimal'
          vmlinux: 'true'
          patches: |
            var/linux-patches/6.18-*
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - run: sudo chmod 666 /dev/kvm
      - name: Test
        run: |
          shopt -s nullglob
          files=("${{ steps.build.outputs.build-dir }}"/boot/vmlinux-*)
          [[ ${#files[@]} -eq 1 ]] || { echo "expected exactly one vmlinux, got ${files[*]}"; exit 1; }

          # Unrestrict unprivileged user namespaces, which is what our
          # tests assume.
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

          VMSH_KERNEL="${files[0]}" cargo test --workspace --all-features -- --include-ignored
  clippy:
    name: Lint with clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --no-deps --workspace --all-targets --all-features --tests -- -A unknown_lints -A deprecated
  rustdoc:
    name: Generate documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: '-D warnings'
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --workspace --no-deps --document-private-items
